[package]
name = "apotheosis"
version = "0.1.0"
authors = ["hydro"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethnum = "1"
nohash-hasher = "0.2.0"